#!/bin/bash

function send()
{
	command="$1"
	shift
	echo "<acritoxinstaller $command> $@"
}

function send_error()
{
	if [ "$#" -gt 1 ]; then
		send error "$@" >&2
	elif [ "$#" -eq 1 ]; then
		send error "$1" "$(tr -d '\n')" >&2
	else
		send error 255 unknown >&2
	fi
	return 1
}

