#!/bin/bash

function init_installer()
{
	[ -f /etc/default/distro ] && . /etc/default/distro
	export FLL_DISTRO_MODE FLL_DISTRO_NAME FLL_LIVE_USER
	mkdir -p /live/filesystem
	[ -d /live/filesystem/usr ] || mount -o ro /dev/loop0 /live/filesystem
	cfg_set hostname "${FLL_DISTRO_NAME}Box"
}

